global:
  resolve_timeout: 5m

route:
  receiver: 'webhook-notifier'
  group_wait: 10s
  group_interval: 5m
  repeat_interval: 3h

receivers:
  - name: 'webhook-notifier'
    webhook_configs:
      - url: 'http://line-reply:5001/alert'
        send_resolved: true
